paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      responses:
        '200':
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos
        '500':
          description: Error interno del servidor

components:
  